import type { SavedContainer, FluidProfile } from "../types";

export const STANDARD_PRESET_CONTAINERS: Omit<SavedContainer, "id">[] = [
  { name: "Teacup / Small Cup", fullVolumeMl: 150 },
  { name: "Standard Mug", fullVolumeMl: 250 },
  { name: "Water Glass", fullVolumeMl: 200 },
  { name: "Large Mug / Tumbler", fullVolumeMl: 350 },
  { name: "Small Water Bottle", fullVolumeMl: 500 },
  { name: "Can of Beverage", fullVolumeMl: 330 },
  { name: "Soup Bowl", fullVolumeMl: 300 },
  { name: "Pint Glass", fullVolumeMl: 568 },
  { name: "Large Sports Bottle", fullVolumeMl: 750 },
  { name: "Graduated Urine Jug", fullVolumeMl: 1000 },
];

export const STANDARD_PRESET_FLUIDS: Omit<FluidProfile, "id">[] = [
  {
    name: "Glass of Water",
    category: "water",
    containerVolumeMl: 200,
    usualServingFraction: 1,
    waterContentPercent: 100,
    waterContentSource: "Verified standard",
    verified: true,
    favourite: true,
  },
  {
    name: "Cup of Tea",
    category: "tea",
    containerVolumeMl: 250,
    usualServingFraction: 1,
    waterContentPercent: 99,
    waterContentSource: "Verified standard",
    verified: true,
    favourite: true,
  },
  {
    name: "Mug of Coffee",
    category: "coffee",
    containerVolumeMl: 250,
    usualServingFraction: 1,
    waterContentPercent: 98,
    waterContentSource: "Verified standard",
    verified: true,
    favourite: true,
  },
  {
    name: "Glass of Fresh Juice",
    category: "juice",
    containerVolumeMl: 200,
    usualServingFraction: 1,
    waterContentPercent: 88,
    waterContentSource: "USDA Food Data",
    verified: true,
    favourite: true,
  },
  {
    name: "Glass of Whole Milk",
    category: "milk",
    containerVolumeMl: 200,
    usualServingFraction: 1,
    waterContentPercent: 87,
    waterContentSource: "USDA Food Data",
    verified: true,
    favourite: true,
  },
  {
    name: "Bowl of Soup",
    category: "soup",
    containerVolumeMl: 300,
    usualServingFraction: 1,
    waterContentPercent: 92,
    waterContentSource: "Clinical fluid intake estimate",
    verified: true,
    favourite: true,
  },
  {
    name: "Nutritional Supplement Drink",
    brand: "Fortisip / Fresubin",
    category: "nutritional_drink",
    containerVolumeMl: 200,
    usualServingFraction: 1,
    waterContentPercent: 78,
    waterContentSource: "Product specification data",
    verified: true,
    favourite: true,
  },
  {
    name: "500ml Water Bottle",
    category: "water",
    containerVolumeMl: 500,
    usualServingFraction: 1,
    waterContentPercent: 100,
    waterContentSource: "Verified standard",
    verified: true,
    favourite: true,
  },
];
